- name: Install criu and python3-criu
  hosts: all
  vars:
    ipinfo:
      - { name: "node0", ip: "192.168.10.3" }
      - { name: "node1", ip: "192.168.10.4" }
      - { name: "node2", ip: "192.168.10.5" }
      - { name: "node3", ip: "192.168.10.6" }
  tasks:
    - name: Install criu package
      dnf:
        name: criu
        state: latest
    - name: Install python3-criu
      dnf:
        name: python3-criu
        state: latest

