- name: Install various packages
  hosts: all
  vars:
    ipinfo:
      - { name: "node0", ip: "192.168.10.3" }
      - { name: "node1", ip: "192.168.10.4" }
      - { name: "node2", ip: "192.168.10.5" }
      - { name: "node3", ip: "192.168.10.6" }
  tasks:
    - name: Install criu package
      dnf:
        name: criu
        state: latest
    - name: Change permission of criu binary
      file:
        path: /usr/sbin/criu
        mode: "4755"
    - name: Install python3-criu
      dnf:
        name: python3-criu
        state: latest
    - name: Install singularity
      dnf:
        name: singularity
        state: latest
    - name: Install python3-root
      dnf:
        name: python3-root
        state: latest
    - name: Install cvmfs-release
      dnf:
        name: https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
        disable_gpg_check: yes
        state: present
    - name: Install CvmFS
      dnf:
        name: cvmfs
        state: latest
    - name: Create cvmfs cache directory
      file:
        path: /cvmfs_cache
        owner: cvmfs
        group: cvmfs
        state: directory
    - name: Setup cvmfs_cache_t context for /cvmfs_cache direcotyr
      community.general.sefcontext:
        target: '/cvmfs_cache(/.*)?'
        setype: cvmfs_cache_t
        state: present     
    - name: Restorecon to apply SELinux policy
      ansible.builtin.command: restorecon -irv /cvmfs_cache
    - name: Configure cvmfs
      copy:
        dest: /etc/cvmfs/default.local
        content:  "CVMFS_REPOSITORIES=\"cms.cern.ch\"\nCVMFS_HTTP_PROXY=DIRECT\nCVMFS_QUOTA_LIMIT=\"30000\"\nCVMFS_CACHE_BASE=\"/cvmfs_cache\""
      notify: restart autofs
    - name: cvmfs_config setup
      ansible.builtin.command: cvmfs_config setup
    - name: cvmfs_config cksetup
      ansible.builtin.command: cvmfs_config chksetup
    - name: cvmfs_config probe
      ansible.builtin.command: cvmfs_config probe
      notify: restart autofs

  handlers:
    - name: restart autofs  
      service: 
        name: autofs
        state: restarted   



