JobBatchName            = SelfCheckpoint_Test_$(Cluster)
executable = example.py
universe   = vanilla
requirements = ( HasSingularity == true )
getenv     = True
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
output = job_$(Process).out
error = job_$(Process).err
log = job_$(Process).log


#requirements = (Machine =?= "node2.intranet.local")
transfer_checkpoint_files = example.checkpoint 
transfer_output_files = finish.txt

+SingularityImage = "/shared/container_images/geant4_wCRIU.sif"
+SingularityBind = "/shared"
+SingularityExtraArgs= "--add-caps all"


checkpoint_exit_code = 85
+WantFTOnCheckpoint = True

notification = Error
notify_user = geonmo@kisti.re.kr

queue 1
